### ISSUE TITLE
WiFi config does not appear to work for AU

### ISSUE THREAD

**Issue by ramoun** [snip/OGN-receiver-RPI-image#14]
Edited the 3 WiFi values for Australia "AU" in the config file, but WiFi does not work.

I can edit via sudo raspi-config and it runs ok.

**Comment by snip** [comment]
Hi,
when you set the "AU" in the OGN config file can you please check what you get in `/etc/wpa_supplicant/wpa_supplicant.conf`? And what do u get when u do it via `raspi-config`?

Thanks

**Comment by ramoun** [comment]
Sure I’ll test an let you know.

Cheers
Steve

**Comment by snip** [comment]
Hi @ramoun, any news about your test?

**Comment by ramoun** [comment]
Hi Seb,

I tested and have it running on 1 station.

I’m not sure of the exact process or steps, but it would be easier to consider it ok, then if I come across it again and can replicate it I open another ticket with the detail.

I tried to close it but it would not let me for some reason, could you do this.

Cheers
Steve

**Comment by snip** [comment]
Sure.
Closing it.

See u.
