### ISSUE TITLE
Image broken?

### ISSUE THREAD

**Issue by bkolb** [snip/OGN-receiver-RPI-image#16]
Hi, 
I just wanted to use the image from here: http://download.glidernet.org/seb-ogn-rpi-image
I am on a Mac. I am using the balenaEtcher to write the flash card. 
The flashing fails and it claims the image is broken. The same happens if I use the build-in Mac image-recovery tool. Any idea?

Thanks

**Comment by snip** [comment]
Hi @bkolb 
No, image is not broken :)

I never used balenaEtcher nor mage-recovery.
On Mac i used Raspberry Pi Imager for macOS (https://www.raspberrypi.org/downloads/) without any issue.
Can you please try it?

See u
--
Seb

**Comment by bkolb** [comment]
Indeed :-) Works. Thx!
