### ISSUE TITLE
Question on tag v0.3

### ISSUE THREAD

**Issue by Karle3** [snip/OGN-receiver-RPI-image#22]
Hello Snip, regarding
[tag v0.3](https://github.com/snip/OGN-receiver-RPI-image/releases/tag/v0.3) i have installed on a Raspi 3B (without plus).
It is connected via ethernet to a DSL-router, WiFi disabled.
The system does stops its alive message every night at about 4:00 am.
See [EDPJ2](https://range.onglide.com/?lat=48.46557&lng=9.67814&zoom=11.4&file=&station=EDPJ2) and
[ognrange](https://ognrange.glidernet.org/#EDPJ,max,lastweek,48.49685_9.63784,15,#80000040:#008000ff,circles;).
May this be caused by the cron job to reboot every morning.
Infos: The LED at Raspi blinks in this case. Its real position is nearby airport EDPJ in the city [eastern](https://range.onglide.com/?lat=48.46557&lng=9.67814&zoom=11.4&file=&station=EDPJ2).
Any idea?
[Karle3](http://karle.lai.de/resp/w3ogn.htm)

**Comment by snip** [comment]
> May this be caused by the cron job to reboot every morning.
Yes there is a nightly reboot in the image.
