### ISSUE TITLE
lost login credentials after install

### ISSUE THREAD

**Issue by realnanuk** [snip/OGN-receiver-RPI-image#26]
I installed the ogn stuff on a new raspi4. After the reboot, I was unable to login again. No password works.

Where I can find the password? I didn't change i intentionally, it has to be done during the install,

Best Regards
René

**Comment by snip** [comment]
Hi René,

by default the password login is disabled.

You need to uncomment the following line (by removing the `#` at the begining) to enable it:
`# piUserPassword="raspberry" # By default pi user login by password is disabled`
