### ISSUE TITLE
Gain and Samplerate setup?

### ISSUE THREAD

**Issue by DG7GJ** [snip/OGN-receiver-RPI-image#27]
I use this SD-Image because the Network connection (HTTP & Telnet) in this Image are more stable against some manual OGN-Instalations and different RPi OS versions I make.

But were can I in this Image setup the Sampelrate and RF-Gain for OGN?

The complete GSM-Stuck in don't use, because my Stick is an RTL-SDR V3 wits TCXO.
But the default Gain of 40dB are too much. I want the Gain to 22.9dB.
The Samplerate I want to switch to 1MHz.

This is in the original Template.conf possible, but in this image the Template.conf are not in use.
And the /boot/OGN-Receiver.conf have another format as Template.conf

Juergen, DG7GJ

**Comment by snip** [comment]
Hi,

you can put in /boot a file named `rtlsdr-ogn.conf` which will be used instead of the autogenerated one.
in this file you can tune it as you want.
