### ISSUE TITLE
Write some documentation

### ISSUE THREAD

**Issue by snip** [snip/OGN-receiver-RPI-image#4]

**Comment by snip** [comment]
French manual by Micro:
http://ognproject.wdfiles.com/local--files/downloads/Installation%20du%20logiciel%20OGN%20%28image%200_2%29%20sur%20un%20raspberry.pdf

Thanks :)

**Comment by elgandoz** [comment]
I can help with this.

**Comment by snip** [comment]
Thanks @elgandoz 
So a french document exist, can you try to do something similar in English?

**Comment by elgandoz** [comment]
Sure thing. 

1. Would be ok if I create the steps in markdown? It's easy to view and edit in github, easy to export in html or pdf or on gitHub pages.
2. will be ok to suggest the use of balenaEtcher to flash? Its interface it's clean and simple and works cross platform (is also recommended by the [official RPi documentation](https://www.raspberrypi.org/documentation/installation/installing-images/README.md))

Also, as proposal, given on the wiki I couldn't find a up to date guide, could we cleanup the your imageCreationSteps.md and make it a guide as well? Adding also some debug information.
I found the wiki confusing, with broken links and no clear step by step guide.

**Comment by snip** [comment]
English documentation writen in ad3f5d3980b674e3f0a0bd8a6697ccdd0dcac540
