### ISSUE TITLE
Report RPi hadware

### ISSUE THREAD

**Issue by snip** [snip/OGN-receiver-RPI-image#9]
Thanks to /proc/device-tree/model

**Comment by elgandoz** [comment]
Hey @snip , I was about to build a receiver, just wondering if this image could work on RPi 3 B+ or, even better, [RPi 3 A+](https://www.raspberrypi.org/products/raspberry-pi-3-model-a-plus/). They both have a 64bit arch.

**Comment by snip** [comment]
Hi, yes B+ is working well and A+ should also works but never tested. Please come back here if you have a feedback with this model. Thanks.

**Comment by elgandoz** [comment]
Hi @snip, unfortunately the RPi 3 A+ doesn't boot.

Connected to a screen, it gets stuck on the [rainbow screen](https://elinux.org/R-Pi_Troubleshooting#Coloured_splash_screen): according to that guide "_it suggests the kernel.img file is failing to boot_". Btw, the same happens with the other image by Konstantin Gründger. 
I would like to remember I am using [RPi 3 A+](https://www.raspberrypi.org/products/raspberry-pi-3-model-a-plus/) (same 64bit architecture of **3B+**).
Raspbian Desktop and Lite works fine.

Therefore I installed Raspbian Stretch Lite (via NOOBS) and proceeded with [your guide](https://github.com/snip/OGN-receiver-RPI-image/blob/master/imageCreationSteps.md):
I wasn't sure about some steps but generally it seemed to be fine, although after rebooting I couldn't log in with ssh, despite setting the configuration in `OGN-receiver.conf`.


I have few questions, that maybe you can help me with:

1. in your image creation steps, are the command supposed to be run as root? should I `sudo su` before?
2. It seems your image it's behind the last [commit](https://github.com/snip/OGN-receiver-RPI-image/commit/f558b136d0ef6ac443c13792dc83f3242364351e): it doesn't include that change
3. Any suggestions about the ssh? is the .conf seems to be ignored
4. Is there any way to know if my Pi receiver is connected to the network? There's any way to debug? How can i make to the [list](http://wiki.glidernet.org/list-of-receivers)? the registration page in one of the old guide is down...

It's a lot to process, but thanks.

**Comment by snip** [comment]
Ok, so it seems there is some specificities on A+ which is not compatible with last year raspbian image.
Everything on https://github.com/snip/OGN-receiver-RPI-image/blob/master/imageCreationSteps.md have to be run as root.
But for a single installation it seems not the easiest way to use this special setup.
If you have a 3B+, you can maybe install my image, turn off read only file system, upgrade the rpi (kernel + os) then turn back the file system as ro. Then plug this micro sd in the 3A+.

**Comment by elgandoz** [comment]
Unfortunately I have no 3B+. I tried to mount your image in VirtualBox to do as you suggested, but I wasn't able to load the image correctly. Regardless, your instructions work. 
I forgot to mention that I don't have the dongle yet: apparently i cannot connect to the network without it.
Now from the web interface (ogn-receiver.local:8081) I get:
```
APRS.Server[0]	-> aprs.glidernet.org:14580
  connected to	85.188.1.173:14580
  connected for		00h00
  KiloBytes sent/received	0/0
APRS.Call	BelcoTest
```
So it seems working, although i found that `00h00` weird.. I'll wait once I have the dongle and report back.

**Comment by snip** [comment]
My need is to find if hardware suport ogn-receiver GPU usage or not.
So we should find a way to know the VideoCore version

Only VideoCore IV is supported by ogn-reciver.
(VideoCore IV on Pi <=3, VideoCore VI on Pi 4)
https://forums.raspberrypi.com/viewtopic.php?f=67&p=1901014

Maybe using `grep Hardware /proc/cpuinfo | awk '{ print $3 }'` we can detect processor and then check from 
https://www.raspberrypi.com/documentation/computers/processors.html
